name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Flutter SDKのセットアップ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      # Flutterのバイナリへのパスを追加
      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      # 依存関係のインストール
      - name: Install dependencies
        run: flutter pub get

      # Flutter Webアプリのビルド
      - name: Build Flutter Web App
        run: flutter build web

      # Firebase Hostingへのデプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARINE_ELEVATOR_383111 }}'
          channelId: live
          projectId: marine-elevator-383111
